# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  # The password associated with the postgres role (username).
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>

test:
  <<: *default
  database: EventPlanning_test

production:
  <<: *default
  database: EventPlanning_production
  username: EventPlanning
  password: <%= ENV["EVENTPLANNING_DATABASE_PASSWORD"] %>
